version: '3'
services:
  datart-dev:
    image: java:8
    hostname: datart-dev
    container_name: datart-dev
    restart: always
    volumes:
      - "/root/docker-compose/datart/datart-dev/datart-server-1.0.0-alpha.0:/datart"
    entrypoint: [ "sh","/datart/bin/datart-server.sh" ]
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: "5g"
networks:
  retech_test:
    external: true